const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const read = name => fs.readFileSync(path.join(__dirname, '..', name), 'utf8');
const nodes = new Map();
const element = () => ({ innerHTML:'',clientWidth:620,classList:{add(){},remove(){},toggle(){}},setAttribute(){},addEventListener(){},querySelector:()=>element(),querySelectorAll:()=>[] });
const get = id => {if(!nodes.has(id))nodes.set(id,element());return nodes.get(id);};
const ctx = vm.createContext({Intl,document:{getElementById:get}});
vm.runInContext(read('site/app.js').replace(/init\(\);\s*$/,''),ctx);
vm.runInContext('selectedChoice = () => "bar"',ctx);
const end='2026-09-29T06:00:00Z';
const channel={channelId:'a',channel:'A',subscriberCount:90};
const history=[{channelId:'a',observedAt:'2026-09-20T06:00:00Z',subscriberCount:100},{channelId:'a',observedAt:'2026-09-25T06:00:00Z',subscriberCount:95},{channelId:'a',observedAt:'2026-09-27T06:00:00Z',subscriberCount:null}];
let rows=ctx.subscriberGrowthRows(history,channel,end,'7');
assert.deepEqual(Array.from(rows,r=>r.subscriberDelta),[-5,null,-10]);
assert(rows.every(r=>r.baselineAt===history[0].observedAt));
assert.equal(rows.at(-1).publishedAt,end);
rows=ctx.subscriberGrowthRows(history,channel,end,'30');
assert.equal(rows[0].subscriberDelta,0);
assert.equal(rows.at(-1).subscriberDelta,-10);
assert(rows.every(r=>r.partialWindow));
assert.equal(ctx.subscriberGrowthRows([],channel,end,'7').length,0);
assert.equal(ctx.subscriberGrowthRows(history,{...channel,hiddenSubscriberCount:true},end,'7').length,0);
assert.equal(ctx.subscriberChange({subscriberCount:0},{subscriberCount:4}),-4);
assert.equal(ctx.subscriberChange({subscriberCount:null},{subscriberCount:4}),null);
assert.equal(ctx.subscriberChange({subscriberCount:4},null),null);
const info={label:'新增订阅（净增）',format:v=>String(v),tick:v=>String(v)};
const series=ctx.channelMetricSeries([], [channel], history,end,'subscriberDelta',info,'7');
ctx.renderTimeSeries(series,'近 7 日','chart','legend');
for(const match of get('chart').innerHTML.matchAll(/cy="([\d.]+)"/g))assert(Number(match[1])>=22&&Number(match[1])<=252,'negative values stay inside chart');
assert(get('chart').innerHTML.includes('data-value="-10"'));
assert(!get('chart').innerHTML.includes('NaN'));
ctx.renderChannelBreakdown(series,'近 7 日');
assert(get('breakdownChart').innerHTML.includes('data-value="-10"'));
assert(!get('breakdownChart').innerHTML.includes('width:-'));
const snapshot=JSON.parse(read('site/data.json'));
const current=snapshot.queries.channel_current.rows.filter(r=>!r.hiddenSubscriberCount&&r.subscriberCount!=null);
const stored=snapshot.queries.channel_history.rows;
const totals={};
for(const period of ['7','30','90','all']){
  const cutoff=period==='all'?-Infinity:Date.parse(snapshot.generatedAt)-Number(period)*86400000;
  let independentlyComputed=0;
  for(const c of current){
    const points=stored.filter(r=>r.channelId===c.channelId&&r.subscriberCount!=null&&Number.isFinite(Number(r.subscriberCount))&&Date.parse(r.observedAt)<=Date.parse(snapshot.generatedAt)).sort((a,b)=>Date.parse(a.observedAt)-Date.parse(b.observedAt));
    const baseline=period==='all'?points[0]:points.filter(r=>Date.parse(r.observedAt)<=cutoff).at(-1)||points[0];
    const expected=baseline?Number(c.subscriberCount)-Number(baseline.subscriberCount):null;
    assert.equal(ctx.subscriberChange(c,ctx.subscriberWindowBaseline(stored,c.channelId,snapshot.generatedAt,period)),expected);
    const pointsForChannel=ctx.subscriberGrowthRows(stored,c,snapshot.generatedAt,period);
    assert.equal(pointsForChannel.at(-1)?.subscriberDelta??null,expected);
    if(expected!=null)independentlyComputed+=expected;
  }
  const breakdown=ctx.channelMetricSeries([],current,stored,snapshot.generatedAt,'subscriberDelta',info,period);
  const aggregate=ctx.aggregateChannelSeries(breakdown,'subscriberDelta',info);
  assert.equal(aggregate.rows.at(-1).subscriberDelta,independentlyComputed);
  totals[period]=independentlyComputed;
}
assert(read('site/index.html').includes('data-value="subscriberDelta"'));
assert(!read('site/index.html').includes('data-value="subscriberCount"'));
console.log('PASS: complete/partial/ALL baselines, no baseline, null/hidden/negative values, chart bounds, and snapshot-to-donut reconciliation',totals);
